name: Publish Website to Web Hosting staging
on:
  push:
    branches:
      - staging
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.seriouslysimplemarketing.com
        username: githubstaging@seriouslysimplemarketing.com
        password: ${{ secrets.FTP_PASSWORD_STAGING }}
        port: 21
